<template>
  <v-card width="100%" :loading="refreshing" elevation-9>
    <v-card-title class="text-h4">
      Basic configuration
      <v-spacer></v-spacer>
      <v-btn icon color="green" @click="refresh()">
        <v-icon>mdi-cached</v-icon>
      </v-btn>
    </v-card-title>
    <v-card-subtitle class="text-subtitle-1 ml-2 mt-2"
      >You can configure in this section the Pythia : Intelligence repository
      <br />
    </v-card-subtitle>
    <v-card-text>
      <v-container>
        <!-- URL of Pythia -->
        <v-row>
          <v-col cols="12" md="4">
            <h3>Pythia URL</h3>
            <p>
              You can change this parameter in the configuration file of Atlas.
              Under config/default.json <br />
            </p>
          </v-col>

          <!-- URL Of pythia -->
          <v-col cols="12" md="6">
            <v-text-field
              v-model="pythiaURL"
              hint="URL of the pythia framework repository (READ ONLY)"
              label="Pythia URL"
              readonly
              required
            ></v-text-field>

            <!-- Error on the URL -->
            <p class="red--text">
              {{ pythiaURLError }}
            </p>
          </v-col>

          <!-- Go to Pythia buttton -->
          <v-col cols="12" md="2">
            <v-btn
              class="mt-3"
              color="charcoal"
              dark
              :disabled="!pythiaURL"
              @click="goToPythia()"
            >
              Go to Pythia
            </v-btn>
          </v-col>
        </v-row>

        <!-- Pythia Status -->
        <v-row>
          <v-col cols="12" md="4">
            <h3>Pythia Status</h3>
            <p>
              Check the status of Pythia. You'll need both to be connected and
              authenticated in order to leverage the full potential of Pythia<br />
            </p>
          </v-col>

          <!-- URL Of pythia -->
          <v-col cols="12" md="8">
            <!-- Status button container  -->
            <v-container fluid>
              <v-row>
                <v-col cols="6" class="text-center">
                  <b class="ma-0">Connection:</b>
                  <v-btn
                    depressed
                    color="primary"
                    readonly
                    block
                    :loading="pythiaLoadingStatus"
                  >
                    {{ pythiaStatus }}
                  </v-btn>
                </v-col>
                <v-col cols="6" class="text-center">
                  <b class="ma-0">Authentication:</b>
                  <v-btn
                    depressed
                    color="primary"
                    readonly
                    block
                    :loading="pythiaLoadingAuthStatus"
                  >
                    {{ pythiaAuthStatus }}
                  </v-btn>
                </v-col>
              </v-row>
            </v-container>
            <!-- Error on the URL -->
            <p class="red--text">
              {{ pythiaStatusError }}
            </p>
          </v-col>
        </v-row>

        <!-- Pythia JWT Creation -->
        <v-row>
          <v-col cols="12" md="4">
            <h3>Pythia Authentication</h3>
            <p>
              Past here the JWT token generated by Pythia to perform
              authenticated request.
            </p>
            <p class="green--text">
              {{
                existPythiatoken
                  ? "A Pythia token has already been configured. Be careful if you need to change it"
                  : ""
              }}
            </p>
            <p class="orange--text">
              {{
                !existPythiatoken
                  ? "No Pythia token has been detected. Apply a valid token to unlock Pythia features."
                  : ""
              }}
            </p>
          </v-col>

          <!-- URL Of pythia -->
          <v-col cols="12" md="8">
            <v-container fluid class="ma-0">
              <!-- Pythia token input -->
              <v-row>
                <v-textarea
                  v-model="pythiaToken"
                  clearable
                  filled
                  clear-icon="mdi-close-circle"
                  label="Pythia Token"
                  hint="Past here the JWT generated with your account."
                ></v-textarea>
              </v-row>

              <v-row class="mt-0">
                <v-col cols="10" class="ma-0">
                  <!-- Error on the URL -->
                  <p class="red--text">
                    {{ pythiaTokenError }}
                  </p>
                </v-col>

                <v-col cols="2" class="ma-0">
                  <v-btn
                    class="mt-3"
                    color="charcoal"
                    dark
                    :disabled="!pythiaURL"
                    @click="applyToken()"
                  >
                    {{ existPythiatoken ? "Apply new Token" : "Apply Token" }}
                  </v-btn>
                </v-col>
              </v-row>
            </v-container>
          </v-col>

          <!-- Go to Pythia buttton -->
          <v-col cols="12" offset-md-4 md="8"> </v-col>
        </v-row>
      </v-container>
    </v-card-text>
  </v-card>
</template>

<script lang="ts">
import Vue from 'vue';
import PythiaUtilController from '@/api/controllers/pythia/PythiaUtilController';

export default Vue.extend({
  name: 'PythiaParametersViewer',

  data: () => ({
    refreshing: false,
    // Url params
    pythiaURL: '',
    pythiaURLError: '',

    // Pythia Status
    pythiaStatus: 'No Status',
    pythiaStatusError: '',
    pythiaLoadingStatus: false,

    // Auth Status
    pythiaAuthStatus: '',
    pythiaAuthStatusError: 'No Status',
    pythiaLoadingAuthStatus: false,

    pythiaToken: '',
    existPythiatoken: false,
    pythiaTokenError: '',
    loadingToken: false,
  }),

  methods: {
    /**
     * Get the url of Pythia
     */
    async getUrl() {
      await PythiaUtilController.getURL()
        .then((res: string) => {
          this.pythiaURL = res;
          this.pythiaURLError = '';
        })
        .catch((err) => {
          this.pythiaURLError = err;
        });
    },

    /**
     * Get the status of Pythia
     */
    async getStatus() {
      if (!this.pythiaURL) {
        this.pythiaStatusError = 'No URL Provided';
        this.pythiaStatus = 'Unreachable';
        return;
      }
      this.pythiaLoadingStatus = true;
      await PythiaUtilController.getStatus()
        .then((res: string) => {
          this.pythiaStatus = res;
          this.pythiaStatusError = '';
        })
        .catch((err) => {
          this.pythiaStatusError = err;
        })
        .finally(() => {
          this.pythiaLoadingStatus = false;
        });
    },

    /**
     * Get the authentication status of Pythia
     */
    async getAuthenticationStatus() {
      if (!this.pythiaURL) {
        this.pythiaAuthStatusError = 'No URL Provided';
        this.pythiaAuthStatus = 'Unreachable';
        return;
      }
      this.pythiaLoadingAuthStatus = true;
      await PythiaUtilController.getAuthenticationStatus()
        .then((res: string) => {
          this.pythiaAuthStatus = res;
          this.pythiaAuthStatusError = '';
        })
        .catch((err) => {
          this.pythiaAuthStatusError = err;
        })
        .finally(() => {
          this.pythiaLoadingAuthStatus = false;
        });
    },

    /**
     * Check the status of the Pythia token
     */
    async getTokenStatus() {
      this.loadingToken = false;
      await PythiaUtilController.getTokenPresence()
        .then((res: boolean) => {
          this.existPythiatoken = res;
          this.pythiaTokenError = '';
        })
        .catch((err) => {
          this.pythiaTokenError = err;
        })
        .finally(() => {
          this.loadingToken = false;
        });
    },

    /**
     * Check the status of the Pythia token
     */
    async applyToken() {
      if (!this.pythiaToken) {
        this.pythiaTokenError = 'You must specify a token.';
        return;
      }

      this.loadingToken = false;
      await PythiaUtilController.postToken(this.pythiaToken)
        .then(() => {
          this.refresh();
          this.pythiaTokenError = '';
          this.token = '';
        })
        .catch((err) => {
          this.pythiaTokenError = err;
        })
        .finally(() => {
          this.loadingToken = false;
        });
    },

    /**
     * Go to pythia
     */
    goToPythia() {
      window.open(this.pythiaURL);
    },

    async refresh() {
      this.refreshing = true;
      try {
        await this.getUrl();
        await this.getStatus();
        await this.getAuthenticationStatus();
        await this.getTokenStatus();
      } finally {
        this.refreshing = false;
      }
    },
  },

  mounted() {
    this.refresh();
  },
});
</script>
